//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeDMD_Updater2.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Description {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Description() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeDMD_Updater2.Resources.Description", typeof(Description).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flash your device from a file on your PC. No check will be performed if the file is adapted to your device (S3, Lilygo S3, etc...)..
        /// </summary>
        internal static string buttonFFile {
            get {
                return ResourceManager.GetString("buttonFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download and flash a firmware adapted to your device with the resolution you have chosen. If the autodetected device is not corresponding to the correct one in the device list, you can change the &quot;S3&quot; and &quot;Lilygo&quot; state by double-clicking it..
        /// </summary>
        internal static string buttonFlash {
            get {
                return ResourceManager.GetString("buttonFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perform an LED test of the selected device (the display should go full red, then full green then full blue)..
        /// </summary>
        internal static string buttonLTest {
            get {
                return ResourceManager.GetString("buttonLTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rescan all the devices connected to your PC. Automatically done when a device has been flashed..
        /// </summary>
        internal static string buttonRescan {
            get {
                return ResourceManager.GetString("buttonRescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfer these parameters to your device..
        /// </summary>
        internal static string buttonSNParameters {
            get {
                return ResourceManager.GetString("buttonSNParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of found devices. It could be something else than an ESP32, but all COM devices are listed to be sure there is no &apos;exotic&apos; ESP32 missing. You can force it to be S3 or Lilygo S3 by double-clicking the corresponding box, the detection is not infallible and once again, &apos;exotic&apos; devices may exist. If the version is written in red, the firmware is not the latest available..
        /// </summary>
        internal static string deviceView {
            get {
                return ResourceManager.GetString("deviceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the brightness of your panel here. [1,15].
        /// </summary>
        internal static string numericBrightness {
            get {
                return ResourceManager.GetString("numericBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the resolution of your panel is 128x64, you can set the vertical position of the display of 4:1 or 3:1 roms on it with this value in pixels. [0,32].
        /// </summary>
        internal static string numericOY {
            get {
                return ResourceManager.GetString("numericOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The clock phase of your panel. [0,1].
        /// </summary>
        internal static string numericPCPhase {
            get {
                return ResourceManager.GetString("numericPCPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The type of drivers (chip) of your panel: 0(SHIFTREG),1(FM6124),2(FM6126A),3(ICN2038S),4(MBI5124),5(SM5266P),6(DP3246_SM5368).
        /// </summary>
        internal static string numericPDriver {
            get {
                return ResourceManager.GetString("numericPDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The I2S speed of your panel. Either 8, 16 or 20..
        /// </summary>
        internal static string numericPISpeed {
            get {
                return ResourceManager.GetString("numericPISpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The latch blanking of your panel. [1,4].
        /// </summary>
        internal static string numericPLBlanking {
            get {
                return ResourceManager.GetString("numericPLBlanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The minimum refresh rate of your panel. [30,120].
        /// </summary>
        internal static string numericPMRRate {
            get {
                return ResourceManager.GetString("numericPMRRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not all the LED matrix displays are the same, the order of the RGB data can be GRB, BGR, RGB,...  With this value you can try different values until the ZeDMD logo is red in the top left, green in the bottom right and blue in the top right of the panel. [0,5].
        /// </summary>
        internal static string numericROrder {
            get {
                return ResourceManager.GetString("numericROrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The delay between 2 transfers for stability. Try to set it as low as possible..
        /// </summary>
        internal static string numericUDelay {
            get {
                return ResourceManager.GetString("numericUDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For USB transfer mode, this will determine the size of the buffer to be transferred at once. The higher, the better for smoothness, the lower, the better for stability. Start low and increase until the display is not stable anymore. [32,1920].
        /// </summary>
        internal static string numericUPSize {
            get {
                return ResourceManager.GetString("numericUPSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The firmware to be downloaded and flashed will be for a panel of 128x32..
        /// </summary>
        internal static string radio12832 {
            get {
                return ResourceManager.GetString("radio12832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The firmware to be downloaded and flashed will be for a panel of 128x64 and you can set the vertical offset below..
        /// </summary>
        internal static string radio12864 {
            get {
                return ResourceManager.GetString("radio12864", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The firmware to be downloaded and flashed will be for a panel of 256x64..
        /// </summary>
        internal static string radio25664 {
            get {
                return ResourceManager.GetString("radio25664", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set transfer mode to USB. For S3 and Lilygo S3, the CDC USB connection will be used, no UART mode will be maintained anymore for these devices. Fill the USBpackage size below, too..
        /// </summary>
        internal static string radioUsb {
            get {
                return ResourceManager.GetString("radioUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the transfer mode as WiFi via TC protocol. Don&apos;t forget to fill the WiFi SSID and WiFi password, too..
        /// </summary>
        internal static string radioWTcp {
            get {
                return ResourceManager.GetString("radioWTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the transfer mode as WiFi via UD protocol, you can then set the UDP delay in ms below. Don&apos;t forget to fill the WiFi SSID and WiFi password, too..
        /// </summary>
        internal static string radioWUdp {
            get {
                return ResourceManager.GetString("radioWUdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password for your WiFi connection to the SSID..
        /// </summary>
        internal static string textPassword {
            get {
                return ResourceManager.GetString("textPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name of your internet WiFi SSID. .
        /// </summary>
        internal static string textSsid {
            get {
                return ResourceManager.GetString("textSsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of available firmware version with more recent ones on top. Choose the one you want to install on your selected device..
        /// </summary>
        internal static string versionList {
            get {
                return ResourceManager.GetString("versionList", resourceCulture);
            }
        }
    }
}
